server:
  port: 8080
  ssl:
    key-store: classpath:idolice.cn.jks
    key-store-password: idolice
    key-store-type: JKS
    key-alias: idolice.cn
spring:
  datasource:
    url: jdbc:mysql://123.206.57.248:3306/moodDiary
    username: root
    password: idolice
    driveClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  redis:
    database: 2
    host: localhost
    port: 6379
    password: idolice