server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 686869
    key-store-type: JKS
    key-alias: tomcatssl

spring:
  datasource:
    url: jdbc:mysql://123.206.57.248:3306/moodDiary
    username: root
    password: idolice
    driveClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
